---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 8112, host: 8112}]
provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: default
    data_bags_path: "test/integration/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/files/encrypted_data_bag_secret"
    run_list:
      - recipe[delugeserver::default]
    attributes:
      config:
        auth: true
        core.conf:
          manage: true
          settings:
            move_completed_path: "/.deluge/complete"
            move_completed: "true"
            allow_remote: "true"
            download_location: "/.deluge/staging"
            utpex: "false"
            dht: "false"
            lsd: "false"
        label.conf: true
      plugin:
        enable: ['AutoAdd', 'Label']
