name 'delugeserver'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures delugeserver'
long_description 'Installs/Configures delugeserver'
version '0.2.2'
