name 'delugeserver'
maintainer 'Adam Linkous'
maintainer_email 'alinkous+support@gmail.com'
license 'all_rights'
description 'Installs/Configures delugeserver'
long_description 'Installs/Configures delugeserver'
version '1.0.1'
